### PR TITLE
VPN Support

### LINKED ISSUE #26: Use with vpn
Could this potentially work with a VPN being up on the phone, and thus the outbound traffic would go out over the VPN utun device (rather than the first cell0 interface)? Does the outbound proxied (socksified) traffic follow the natural routing table in place on the phone (if the VPN interface is the default gw)? 

Thanks 🙂

### PR DESCRIPTION
**Pull request by regulad**
If USE_PHONE_VPN is True, use a utun interface if it is available to route. If not, silently fallback to existing cell interfaces. Tested working.

Closes #26

### CODE REVIEW

**Comment by ParkerrDev** [comment]
To be clear, is this VPN support for a VPN on the iOS device or the connected devices? If so what protocol and port should be used?
What VPN are you using that works with this?

**Comment by regulad** [comment]
This commit simply allows requests made to the proxy server on the iOS device to pass through the VPN. I used Tailscale running on my iOS device to test.

**Comment by nneonneo** [comment]
Thanks for the contribution! I'll test it out with my VPN tomorrow and let you know if there are any changes needed.

**Comment by nneonneo** [comment]
Verified to work with a Cisco Anyconnect VPN enabled - thanks for the nice contribution!

**Comment by Ayaan7345** [comment]
Im also using tails but was not able to connect to it because i got the error Captive Portal Detected. Im using a portable router for my setup. did you add your tails DNS into the code?

**Comment by regulad** [comment]
The proxy always uses a generic Google DNS. You can modify it yourself to
use a better DNS server for your setup.

**Comment by Ayaan7345** [comment]
Are you able to share an example of your config that you used tails with what did you change ?

**Pull request merged**
